### PR TITLE
setguide fix

### PR DESCRIPTION
**Pull request by BeckyDTP**

### CODE REVIEW

**Comment by kevinhendricks** [comment]
Is this the single change you want us to make?

https://github.com/Sigil-Ebook/Sigil/pull/554/commits/846edd7391452dabbdcb7e82fbf300508fa54f92

If so, I can merge just that if you want.

**Comment by BeckyDTP** [comment]
Yes of course. Unfortunately, my branch is messy and hence the problems. I still don't fully understand github.

**Comment by kevinhendricks** [comment]
The easiest way to make a pull request is to make a full clone locally of current master and then apply the changes/fixes you want and then make the request.

Alternatively, you can make your own changes first then do a git pull from master before making the pr.

I will make that change tomorrow once I am back at a Desktop machine.

Thanks,

**Comment by BeckyDTP** [comment]
Thank you.
I know the theory, but I do it too rarely and then I make mistakes. I need to practice a little.

**Comment by dougmassay** [comment]
It was a big learning curve for me, too. Being away from it for a while makes it easy to forget, too! I take copious notes that I can refer to. :)

**Comment by kevinhendricks** [comment]
I can wait for a new PR with just the change you want us to make.  Even your last attempt still had appveyor and base.ts changes in the mix.  

Just let me know if you want to try again.  If not, tomorrow I will make that one-line fix.

Thanks

**Comment by BeckyDTP** [comment]
I did a separate PR.

**Pull request closed without merging**
