### PR TITLE
Fix for git-commit icon in main theme

### PR DESCRIPTION
**Pull request by BeckyDTP**
Fix for rasterize

git-commit-rasterize

### CODE REVIEW

**Comment by dougmassay** [comment]
Is this just an image tweak? I don't see any weirdness in the old one, but then I don't see a well as I used to, either! :)

**Comment by BeckyDTP** [comment]
Look here:
git-commit-rasterize-big

**Comment by dougmassay** [comment]
I still don't understand. I don't see that horizontal line (or any of those jagged raster edges) in the current git-commit.svg no matter how big I blow it up. But I'll take your word it needs fixing. :)

**Comment by BeckyDTP** [comment]
The icon consisted of two elements - a triangle at the top and a rectangle below. Together they formed an arrow.
When the icons were in PNG files, the problem didn't exist.
When I saved them as SVG, the problem was not visible either, but when Qt rasterizes the icons on the toolbar - both elements building the arrow got an additional border, which I only noticed today.

**Comment by dougmassay** [comment]
I guess I didn't realize Qt was rasterizing them. I assumed it was just downscaling the svg. I certainly can't see any of the artifacts you mention with the naked eye on Linux or Windows at 3840 x 2160.

**Comment by BeckyDTP** [comment]
I can only assume that it is related to a specific situation: operating system + video card + drivers + screen resolution + something else = visible artifact in this icon.
Since I was able to "catch" the problem in the screenshot before, it definitely existed and is now fixed.

**Pull request merged**
