### PR TITLE
fix various typos 

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -q 3 -S ./3rdparty,*.ts,*.dic,*.aff -L doubleclick,pres,te,varn`

### CODE REVIEW

**Comment by luzpaz** [comment]
Please review cc2b257 commit closely

**Comment by dougmassay** [comment]
Not really much of a fan of large, purely cosmetic pull requests (especially ones that seek to correct code comment typos). We're also currently too deep into a new release process to make any changes now. We'll review later.

**Comment by kevinhendricks** [comment]
Thank you for your efforts.  I agree here.  We will only commit fixes for typos in actual source code itself or in documentation.  Typos in comments are meaningless but changes there can prevent third party patches from ever applying, and make other actual later changes based afterwards confusing, all due to essentially meaningless changes.

After our next release, I will go through these to fix typos in build docs and  actual code where needed.

**Comment by kevinhendricks** [comment]
Okay, I had a free moment to examine these closely.  We definitely want "fix followup source typos" and if you create a separate pull for that part I will go ahead and merge it straightaway.

The first longer patch really needs to be split into the parts the end user sees, and the parts only the devs sees (i.e. comments).  No changes will be made to comments.  Any fixes will be limited to the things an actual user can see to minimize changes that add no value.

I will walk through your first patch, fixes just things user facing.  If youwould prefer it, if you split out those from your first commit, I would be happy to merge it otherwise I will just change things by hand.

**Comment by luzpaz** [comment]
I'll make the requested changes you need. Will work on it in a few minutes

**Comment by kevinhendricks** [comment]
No rush.  I am tied up today and happy to wait for those separate pull requests.

Thank you!

**Comment by luzpaz** [comment]
'end user sees' does this include doxygen (comments that will become documentation) ?

**Comment by kevinhendricks** [comment]
Can you supply a specific example?

**Comment by dougmassay** [comment]
They're talking about the formatted comments proceeding the functions in the header files (comments, parameter documentation, etc...) that can be used to automatically generate documentation with doxygen.

I'm not sure anyone's ever created documentation for Sigil that way (and we haven't kept up the practice anyway).

**Comment by luzpaz** [comment]
On second thought, I will defer the rest of the commits to y'all to figure out what you want to keep or not.

**Comment by kevinhendricks** [comment]
Again, nothing in comments as we do not generate docs from them for Sigil

**Comment by kevinhendricks** [comment]
Closing this as the current pr is not really what we want here.

**Pull request closed without merging**
