### PR TITLE
Typo in entity description

### PR DESCRIPTION
**Pull request by BeckyDTP**

### CODE REVIEW

**Comment by kevinhendricks** [comment]
If you look at the other entries nearby it says capital letter s not S so we should treat all of these consistently.

**Comment by BeckyDTP** [comment]
You're right. I will fox these other places too.

**Comment by kevinhendricks** [comment]
When you think you have finished, please let me know and I will merge your PR.

Thank you!

**Comment by BeckyDTP** [comment]
There were only three places. All fixed.

**Comment by kevinhendricks** [comment]
Thank you!

**Pull request merged**
