### PR TITLE
Optncx

### PR DESCRIPTION
**Pull request by kevinhendricks**
merge optncx into master via a pull request since it appears to be possible

### CODE REVIEW

**Comment by kevinhendricks** [comment]
I restored the branch just for the record.  We should probably disable optncx ci builds before we remove the branch.

**Comment by dougmassay** [comment]
Hi Kevin,

Removing the optincx line from the on: section of the appveyor and Travis
yaml files should be enough to do it. I'm on my phone's data-plan for the
moment if you want to do it. Otherwise, I'll do it when my internet is back
up and running. Damn service has been very flaky of late!

**Comment by dougmassay** [comment]
In both branches just to be safe. Feel free to use [skip ci] for both
commits since we already know it builds.

**Comment by dougmassay** [comment]
Hi Kevin,

Should be safe to kill the optincx branch now. There's one unmerged commit
there, but it's just the yaml files I modified. Probably overkill on my
part, but...

Thanks,
Doug

**Comment by dougmassay** [comment]
optcx!! I have no idea why my auto-correct wants to change it to optincx!
It's not like THAT'S a real word either.

**Comment by kevinhendricks** [comment]
I snorted my beer when I read that!  Autocorrect should be viciously killed in all forms.  I have painstakingly typed complete e-mails with just one finger to look up and find complete gibberish due to autocorrect!

Take care,

Kevin

**Comment by dougmassay** [comment]
I have it (autocorrect) disabled on all my devices but this phone. And that's only because I just haven't gotten around to it yet! ;)

**Comment by kevinhendricks** [comment]
It will not let me delete the branch directly on GitHub since your last commit made it active again!  I will delete it via the command line tomorrow and push it there.

Take care,

Kevin

**Comment by dougmassay** [comment]
Yeah... sorry about that. After I pushed that change I wondered if that
unmerged commit might keep that from working from the web interface.

**Pull request merged**
