### PR TITLE
Replace deprecated setTimeSpec() calls

### PR DESCRIPTION
**Pull request by TheComputerGuy96**

### CODE REVIEW

**Comment by kevinhendricks** [comment]
Unfortunately, the correct solution for the "unused variable" is to properly use it at the end of that routine.  That said, the GetInfo routine is a new addition yesterday and is testable but not complete.

I have pushed the proper solution to master.

Please remove your incorrect unused variable "fix", and I will go ahead and merge the remaining part of your PR.

**Comment by kevinhendricks** [comment]
Actually since Sigil supports as far back as Qt 6.4.2 and QTimeZone did not finish that class until Qt 6.5, and because setTimeSpec will not even be deprecated until 6.9,  I am not sure we can merge your PR at all.  It would need to be tested on Qt 6.4 to see if it works properly.

**Comment by dougmassay** [comment]
I approved the Linux CI build of this PR, so we should at least see if it will build with Qt6.4

**Comment by kevinhendricks** [comment]
So it appears to work with Qt 6.4.
So we can merge this once amended to remove the improper fix for the "unused variable".

**Comment by dougmassay** [comment]
It builds ok, but I'm not sure that's enough. It wouldn't be the first time I saw a Qt problem that didn't manifest until runtime. ;) How would I test that this works with a Qt6.4 based Sigil?

That said: we can probably merge the PR for now. If we run into problems later, we can deal with it.

**Comment by kevinhendricks** [comment]
But we only want 7eba71a

We do not want 057540b, as that variable is no longer unsed.

**Comment by dougmassay** [comment]
Got it. So we're still waiting for PR to be changed to reflect that.

**Comment by kevinhendricks** [comment]
Yes, unless you know how to merge only a part of a PR!

**Comment by dougmassay** [comment]
I might be able to cherry-pick the one commit if they don't get back to us.

**Comment by kevinhendricks** [comment]
You can test it by editing any epub and saving it and then check the metadata for modification time to see if it fits the required format and seems reasonable.

**Comment by kevinhendricks** [comment]
Let's give them a chance to fix the PR, otherwise we will cherry pick the part we want.

**Comment by dougmassay** [comment]
Looks like the PR might be incompatible with the current HEAD. Is that just because of the commit in question?

**Comment by kevinhendricks** [comment]
Yes, it removed an "unused" variable in the newly created GetInfo() but instead of removing it, it should have been used to restore BoikBrower state.

**Comment by TheComputerGuy96** [comment]
I was actually sleeping during this time (anyway I removed the unused variable change)

**Comment by kevinhendricks** [comment]
Thank you!

**Pull request merged**
