### PR TITLE
Write EPUB everywhere in interface

### PR DESCRIPTION
**Pull request by bershan2**
In src/Resource_Files/ts/base.ts replace all occurrences of "Epub" in interface text with "EPUB", which is the way IDPF writes it.
Translations left unchanged: since they will be pulled from transifex.com, "EPUB" correction has to be done there.

### CODE REVIEW

**Comment by kevinhendricks** [comment]
Sorry. No interested.  The original IDPF symbol and name was ePub.  They have changed its case repeatedly.

**Comment by bershan2** [comment]
Do you mean you'll reject any commit with ePub/epub/EPUB/etc. standardization in principle? Or do you dislike how "EPUB" looks? I just wish the UI was consistent and could change the case to the one you like best, if you'll accept such commit.

**Comment by kevinhendricks** [comment]
yes, I have no interest in any pull requests to standardize on any single  version of epub.  

That said pull requests for real typos and not opinions are welcome

**Comment by kevinhendricks** [comment]
Also, base.ts is a generated file from the set of acutal source code and nothing should be changed in it.  Instead the underlying source code the typo was in, has to be fixed.  I pushed a fix for src/Dialogs/MetaEditor.cpp to fix your "asequence" to "a sequence" in the right place since I was fixing a different typo reported via transifex issues.

**Pull request closed without merging**
