### PR TITLE
Change box size of Preferences color list box

### PR DESCRIPTION
**Pull request by Axa-Ru**
Changed form PAppearanceWidget.ui

PAppearanceWidget ui  master  - Qt Creator_040

### CODE REVIEW

**Comment by dougmassay** [comment]
I'd rather not. The 475 height has proven to ensure that the preference dialog fits the screen on all platforms at most resolutions (regardless of any highdpi scaling). I don't see the need for a blanket 12 pixel increase in the size of one widget.

**Comment by dougmassay** [comment]
Also, why the need for the color list widget to be able to expand indefinitely?

**Comment by dougmassay** [comment]
All this seems to achieve (based on my local testing) is making the color list fill the grid layout horizontally. But all of that increased space is completely empty space. Don't all the attributes already fit with room to spare horizontally in the list widget?

**Comment by kevinhendricks** [comment]
Agreed.  Unless there is clear benefit/reason behind this change (that I am not seeing either), we should probably close this.

**Comment by dougmassay** [comment]
I'll give them a bit of time to make the case for why filling the extra horizontal space (with empty space) would be advantageous, or important, otherwise I'm in agreement. Unless I'm missing something, this will likely be closed.

**Comment by BeckyDTP** [comment]
If I can add something:
* I suggest leaving the height of the entire Preferences window.
* Also, the width of the color window should remain unchanged.
* However, I like stretching the color window and people constantly "tuning" the colors will be satisfied.

Patch:
[patch.txt](https://github.com/Sigil-Ebook/Sigil/files/4428084/patch.txt)

**Comment by dougmassay** [comment]
Your third bullet point makes absolutely no sense to me. Why would people who tune colors (constantly or rarely) care in the least that an ocean of empty space was added to the right of the items in the list? It makes absolutely no difference in the ability to easily tweak the colors.

**Comment by BeckyDTP** [comment]
No, no!
My patch not change width the color list.

The preferences window remembers your size and tab, so if you can see all the colors immediately after pressing F5 (without using the scroll bar in the color list) - life becomes easier.

Of course this is only a cosmetic change, but - I admit - I missed the possibility of extending (vertical) the list of colors.

sigil-preferences-colors-idea

**Comment by dougmassay** [comment]
I'm closing this pull request either way. If someone can create another that maintains the 475 height minimum of the preference widget; doesn't needlessly add an ocean of empty space to the right of list, but allows the color list to expand more in the vertical direction, I'll be happy to include that change (though it seems a little nitpicky to me).

**Comment by BeckyDTP** [comment]
The author of the pull request is probably from Russia.
Look at the interface in Russian and you will understand that his proposal was dictated by the improvement of UI for Russian-speaking users.
I suggest adding a few pixels of the width of the color list to avoid horizontal scrollbar in Russian + vertical expansion.
I can prepare such a pull request.

sigil-preferences-colors-russian

**Comment by dougmassay** [comment]
Yes. I see that the horizontal scrollbar is necessary when Russian is the interface language. Submit your request and I will test it on two platforms. The initial preference dialog (when no user preferences exist) still need to default to maintaining the current height minimums. I can't have the appearances preference widget defaulting to going beyond what will fit in an 800x600 screen resolution for new users.

**Comment by dougmassay** [comment]
Closing in favor of the less intrusive #520

**Pull request closed without merging**
