### PR TITLE
Spell check: Ignore soft hyphens in words

### PR DESCRIPTION
**Pull request by BeckyDTP**

### CODE REVIEW

**Comment by kevinhendricks** [comment]
Looks good.   As soon as tests builds pass, I will merge it.

**Comment by dougmassay** [comment]
Any need to include zwj characters while we're at it?

**Comment by kevinhendricks** [comment]
A dictionary that has words that use zwj should have that character its .aff in the wordchars line. Unlike the soft hyphen which is not a valid char in any language.  Are words the use zwj validly spelled without it?

**Comment by kevinhendricks** [comment]
I will merge this and we can add zwj if it turns out to be needed.

**Comment by dougmassay** [comment]
Makes sense. I definitely defer to your expertise on dictionary matters. :)

**Pull request merged**
